### ISSUE TITLE
Feature: Add a color by column

### ISSUE THREAD

**Issue by Spoutnik97** [huacnlee/zed-csv#2]
I find very useful the vscode extension to highlight each column with its own color.
I help me to see which number is for which columns on big csv files

<img width="262" alt="image" src="https://github.com/huacnlee/zed-csv/assets/30442116/436c9f03-6d95-441a-8121-8582c6ede313">

**Comment by huacnlee** [comment]
This idea is on the way, and still in discussion. 

See my comment on this PR:
https://github.com/zed-industries/extensions/pull/537

**Comment by huacnlee** [comment]
Search "rainbow csv" on Zed extension page.
